import type { Metadata } from 'next';
import { Joti_One } from 'next/font/google';
import './globals.css';

const jotiOne = Joti_One({
  variable: '--font-joti-one',
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jotiOne.variable} bg-line-paper antialiased`}>
        {children}
      </body>
    </html>
  );
}
